# Generated by Django 5.0.3 on 2024-04-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/')),
                ('name', models.CharField(max_length=255)),
                ('rating_stars', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('price_rupees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
