# Generated by Django 5.0.3 on 2024-04-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
