# Generated by Django 5.0.3 on 2024-04-23 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_deliveryoption_remove_cart_deliveryoptionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_option',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.deliveryoption'),
        ),
    ]
