# Generated by Django 5.0.3 on 2024-04-23 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_cart_delivery_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.deliveryoption'),
        ),
    ]
