# Generated by Django 5.0.3 on 2024-04-24 13:01

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='default_delivery_option_id',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.deliveryoption'),
        ),
    ]

