# Generated by Django 5.0.3 on 2024-04-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_cart_default_delivery_option_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='default_delivery_option_id',
            new_name='default_delivery_option',
        ),
    ]
