# Generated by Django 5.0.3 on 2024-04-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_default_delivery_option_id_cart_default_delivery_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='default_delivery_option',
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_option',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.deliveryoption'),
        ),
    ]
