# Generated by Django 5.0.3 on 2024-05-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_cart_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='default_delivery_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_option', to='home.deliveryoption'),
        ),
    ]
