# Generated by Django 5.0.3 on 2024-05-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_cart_default_delivery_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='default_delivery_option',
        ),
    ]
