# Generated by Django 5.0.3 on 2024-05-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_cart_delivery_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoption',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
