# Generated by Django 5.0.3 on 2024-05-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.deliveryoption'),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
