# Generated by Django 5.0.3 on 2024-05-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_customer_locality_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
    ]
