# Generated by Django 5.0.3 on 2024-05-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_orderplaced_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_placed_addresses', to='home.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_placed_cities', to='home.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='orderId',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_placed_states', to='home.customer'),
            preserve_default=False,
        ),
    ]
