# Generated by Django 5.0.3 on 2024-05-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_orderplaced_address_orderplaced_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='state',
        ),
    ]
