# Generated by Django 5.0.3 on 2024-05-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_orderplaced_address_remove_orderplaced_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='ordered_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
