# Generated by Django 5.0.3 on 2024-05-09 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_orderplaced_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='delivery_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.deliveryoption'),
        ),
    ]
