# Generated by Django 5.0.3 on 2024-05-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_orderplaced_delivery_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='delivery_option',
        ),
    ]
