# Generated by Django 5.0.3 on 2026-10-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_orderplaced_shipping_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(db_index=True, max_length=6)),
                ('office', models.CharField(max_length=150)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('division', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
